package com.solarized.firedown.utils;


import android.util.Log;

import com.solarized.firedown.data.entity.GeckoInspectEntity;
import com.solarized.firedown.ffmpegutils.FFmpegEntity;
import com.solarized.firedown.ffmpegutils.FFmpegStreamInfo;


import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.*;

public class JsonHelper {

    private static final String TAG = JsonHelper.class.getSimpleName();

    public static GeckoInspectEntity parse(JSONObject json) {
        if (json == null) return null;
        try {
            GeckoInspectEntity entity = new GeckoInspectEntity();
            entity.setMessage(json);
            entity.setUrl(parseUrl(json));
            entity.setGeckoType(json.optString("type", ""));
            entity.setDescription(json.optString("description", ""));
            entity.setTabId(json.optInt("tabId", 0));
            entity.setName(json.optString("name", null));
            entity.setRequestId(json.optString("requestId", ""));
            entity.setImg(json.optString("img", null));
            entity.setOrigin(parseOrigin(json));
            entity.setRequestHeaders(parseHeaders(json));
            entity.setIncognito(json.optBoolean("incognito", false));

            // Parse variants with SABR data if available
            JSONObject sabr = json.optJSONObject("sabr");
            entity.setVariants(parseVariants(json.optJSONArray("variants"), sabr));

            // Store SABR shared data (URL + config + PO token) on the entity for
            // BrowserDownloadEntity to pick up in GeckoInspectTask
            if (sabr != null) {
                entity.setSabrUrl(sabr.optString("serverAbrStreamingUrl", null));
                entity.setSabrConfig(sabr.optString("videoPlaybackUstreamerConfig", null));

                // PO token generated by BotGuard via bgutils-js
                String poToken = sabr.optString("poToken", null);
                if (poToken != null && !poToken.isEmpty() && !"null".equals(poToken)) {
                    entity.setSabrPoToken(poToken);
                    Log.d(TAG, "PO token set: " + poToken.length() + " chars");
                }
                String clientVersion = sabr.optString("clientVersion", null);
                if (clientVersion != null && !clientVersion.isEmpty() && !"null".equals(clientVersion)) {
                    entity.setSabrClientVersion(clientVersion);
                }
            }

            // Duration from innertube (lengthSeconds * 1000 in background.js)
            long duration = json.optLong("duration", 0);
            if (duration > 0) {
                entity.setDuration(duration);
            }

            return entity;
        } catch (Exception e) {
            Log.e(TAG, "parse", e);
            return null;
        }
    }

    private static String parseUrl(JSONObject json) throws JSONException {
        if (json.has("url")) return json.getString("url");
        if (json.has("videoUrl")) return json.getString("videoUrl");
        return null;
    }

    private static String parseOrigin(JSONObject json) {
        String origin = null;
        if (json.has("originUrl")) {
            origin = json.optString("originUrl", "");
        } else if (json.has("origin")) {
            origin = json.optString("origin", "");
        }
        return "null".equals(origin) ? null : origin;
    }

    private static Map<String, String> parseHeaders(JSONObject json) throws JSONException {
        JSONArray headers = null;
        if (json.has("requestHeaders")) {
            headers = json.getJSONArray("requestHeaders");
        } else if (json.has("headers")) {
            headers = json.getJSONArray("headers");
        }
        return headers != null ? headersArrayToMap(headers) : null;
    }

    /**
     * Parses a JSON array of stream variants into FFmpegEntity objects.
     * When SABR data is available, each variant gets its SABR FormatId fields
     * populated so the SabrStrategy can download at the selected quality.
     *
     * Expected JSON shape per variant:
     * { "url": "...", "audioUrl": "...", "width": N, "height": N,
     *   "itag": N, "audioItag": N,
     *   "videoLastModified": "...", "videoXtags": "...",
     *   "audioLastModified": "...", "audioXtags": "...",
     *   "videoCodec": "...", "audioCodec": "..." }
     *
     * SABR JSON (shared across all variants):
     * { "serverAbrStreamingUrl": "...", "videoPlaybackUstreamerConfig": "...",
     *   "poToken": "...",
     *   "formats": [ { "itag": N, "lastModified": "...", "xtags": "...",
     *                   "audioTrackId": "...", ... } ] }
     */
    public static ArrayList<FFmpegEntity> parseVariants(JSONArray jsonArray, JSONObject sabr) {
        if (jsonArray == null) return null;

        // Build SABR format lookup: itag → format JSON (for lastModified/xtags/audioTrackId)
        Map<Integer, JSONObject> sabrFormatMap = null;
        if (sabr != null) {
            JSONArray sabrFormats = sabr.optJSONArray("formats");
            if (sabrFormats != null) {
                sabrFormatMap = new HashMap<>();
                for (int i = 0; i < sabrFormats.length(); i++) {
                    JSONObject fmt = sabrFormats.optJSONObject(i);
                    if (fmt != null) {
                        sabrFormatMap.put(fmt.optInt("itag", 0), fmt);
                    }
                }
            }
        }

        ArrayList<FFmpegEntity> variants = new ArrayList<>();
        for (int i = 0; i < jsonArray.length(); i++) {
            try {
                JSONObject v = jsonArray.getJSONObject(i);
                int width = v.optInt("width", 0);
                int height = v.optInt("height", 0);

                FFmpegEntity stream = new FFmpegEntity();
                stream.setStreamUrl(v.optString("url", ""));
                stream.setStreamAudioUrl(v.optString("audioUrl", null));
                stream.setCodecType(FFmpegStreamInfo.CodecType.VIDEO.getValue());
                stream.setVideoStreamNumber(0);
                stream.setAudioStreamNumber(0);

                String videoCodec = v.optString("videoCodec", null);
                String audioCodec = v.optString("audioCodec", null);
                if (videoCodec != null && !videoCodec.isEmpty()) stream.setVideoCodec(videoCodec);
                if (audioCodec != null && !audioCodec.isEmpty()) stream.setAudioCodec(audioCodec);

                if (height > 0 && width > 0) {
                    stream.setStreamDescription(
                            String.format(Locale.US, "%dp (%d x %d)", height, width, height));
                    stream.setInfo(String.format(Locale.US, "%dp", height));
                }

                // Populate SABR FormatId fields from variant + SABR format lookup
                int videoItag = v.optInt("itag", 0);
                int audioItag = v.optInt("audioItag", 0);

                if (videoItag > 0 && audioItag > 0 && sabrFormatMap != null) {
                    stream.setSabrVideoItag(videoItag);
                    stream.setSabrAudioItag(audioItag);
                    stream.setSabrTargetHeight(height);

                    // Video FormatId: prefer variant-level fields, fall back to SABR format lookup
                    stream.setSabrVideoLastModified(
                            v.optString("videoLastModified",
                                    sabrFormatMap.containsKey(videoItag)
                                            ? sabrFormatMap.get(videoItag).optString("lastModified", "0") : "0"));
                    stream.setSabrVideoXtags(
                            v.optString("videoXtags",
                                    sabrFormatMap.containsKey(videoItag)
                                            ? sabrFormatMap.get(videoItag).optString("xtags", "") : ""));

                    // Audio FormatId
                    JSONObject audioFmt = sabrFormatMap.get(audioItag);
                    stream.setSabrAudioLastModified(
                            v.optString("audioLastModified",
                                    audioFmt != null ? audioFmt.optString("lastModified", "0") : "0"));
                    stream.setSabrAudioXtags(
                            v.optString("audioXtags",
                                    audioFmt != null ? audioFmt.optString("xtags", "") : ""));
                    if (audioFmt != null) {
                        stream.setSabrAudioTrackId(audioFmt.optString("audioTrackId", ""));
                    }
                }

                variants.add(stream);
            } catch (JSONException e) {
                Log.e(TAG, "parseVariants", e);
            }
        }
        return variants;
    }

    public static Map<String, String> headersArrayToMap(JSONArray jsonArray) throws JSONException {
        Map<String, String> map = new HashMap<>();
        for (int i = 0; i < jsonArray.length(); i++) {
            JSONObject obj = jsonArray.getJSONObject(i);
            map.put(obj.getString("name"), obj.getString("value"));
        }
        return map;
    }

    public static Map<String, Object> toMap(JSONObject object) throws JSONException {
        Map<String, Object> map = new HashMap<>();
        Iterator<String> keys = object.keys();
        while (keys.hasNext()) {
            String key = keys.next();
            map.put(key, fromJson(object.get(key)));
        }
        return map;
    }

    public static List<?> toList(JSONArray array) throws JSONException {
        List<Object> list = new ArrayList<>();
        for (int i = 0; i < array.length(); i++) {
            list.add(fromJson(array.get(i)));
        }
        return list;
    }

    private static Object fromJson(Object json) throws JSONException {
        if (json instanceof JSONObject) {
            return toMap((JSONObject) json);
        } else if (json instanceof JSONArray) {
            return toList((JSONArray) json);
        } else {
            return json;
        }
    }
}