package com.solarized.firedown.lanshare;

import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Log;

import androidx.annotation.Nullable;

import java.math.BigInteger;
import java.security.KeyPairGenerator;
import java.security.KeyStore;
import java.util.Calendar;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.security.auth.x500.X500Principal;

/**
 * TLS identity for {@link LanShareServer} — a per-install, self-signed EC
 * P-256 certificate generated by AndroidKeyStore (which mints the
 * self-signed X.509 alongside the keypair, so no BouncyCastle / no hand-
 * rolled DER, and the private key never leaves the keystore).
 *
 * <p><b>Threat model this buys:</b> the receiver's browser can't verify a
 * self-signed cert (one "connection not private" interstitial, expected and
 * explained on the sender sheet), but the handshake still negotiates
 * ephemeral-key cipher suites (ECDHE) — so a PASSIVE sniffer on hostile
 * Wi-Fi gets ciphertext it can never decrypt, even if it records everything:
 * the file bytes, the PIN in the QR URL, and the session cookie all stop
 * being readable off the air. What it deliberately does NOT defeat is an
 * ACTIVE man-in-the-middle presenting its own self-signed cert — the
 * receiver has no way to tell the two apart; pinned-cert verification needs
 * a native client on both ends (the LocalSend-protocol upgrade path).
 *
 * <p>Per-install (not per-session) on purpose: the fingerprint stays stable
 * across shares, so a browser's stored "proceed" exception keeps working.
 *
 * <p>Failure here is non-fatal by design — {@link #getServerContext()}
 * returns null and the server falls back to plain HTTP (the pre-TLS
 * behavior) rather than breaking sharing on exotic keystore implementations.
 */
public final class LanShareTls {

    private static final String TAG = LanShareTls.class.getSimpleName();
    private static final String KEY_ALIAS = "lanshare-tls";
    private static final String ANDROID_KEY_STORE = "AndroidKeyStore";
    private static final int CERT_VALIDITY_YEARS = 20;

    private static SSLContext sCachedContext;

    private LanShareTls() {
    }

    /**
     * The server-side SSLContext backed by the keystore identity, or null
     * when TLS can't be set up (caller falls back to plain HTTP).
     */
    @Nullable
    public static synchronized SSLContext getServerContext() {
        if (sCachedContext != null) {
            return sCachedContext;
        }
        try {
            KeyStore keyStore = KeyStore.getInstance(ANDROID_KEY_STORE);
            keyStore.load(null);
            if (!keyStore.containsAlias(KEY_ALIAS)) {
                generateIdentity();
            }
            KeyManagerFactory keyManagerFactory =
                    KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keyStore, null);
            SSLContext context = SSLContext.getInstance("TLS");
            context.init(keyManagerFactory.getKeyManagers(), null, null);
            sCachedContext = context;
        } catch (Exception e) {
            Log.e(TAG, "TLS identity unavailable — LAN share falls back to plain HTTP", e);
        }
        return sCachedContext;
    }

    private static void generateIdentity() throws Exception {
        Calendar notBefore = Calendar.getInstance();
        notBefore.add(Calendar.DAY_OF_YEAR, -1);
        Calendar notAfter = Calendar.getInstance();
        notAfter.add(Calendar.YEAR, CERT_VALIDITY_YEARS);

        KeyPairGenerator generator = KeyPairGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_EC, ANDROID_KEY_STORE);
        KeyGenParameterSpec spec = new KeyGenParameterSpec.Builder(
                KEY_ALIAS, KeyProperties.PURPOSE_SIGN)
                .setDigests(KeyProperties.DIGEST_SHA256, KeyProperties.DIGEST_SHA384,
                        KeyProperties.DIGEST_SHA512)
                .setCertificateSubject(new X500Principal("CN=Firedown LAN share"))
                .setCertificateSerialNumber(BigInteger.valueOf(System.currentTimeMillis()))
                .setCertificateNotBefore(notBefore.getTime())
                .setCertificateNotAfter(notAfter.getTime())
                .build();
        generator.initialize(spec);
        generator.generateKeyPair();
    }
}
