package com.solarized.firedown.lanshare;

import android.security.keystore.KeyGenParameterSpec;
import android.security.keystore.KeyProperties;
import android.util.Log;

import androidx.annotation.Nullable;

import java.math.BigInteger;
import java.net.Socket;
import java.security.KeyPairGenerator;
import java.security.KeyStore;
import java.security.Principal;
import java.security.PrivateKey;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.util.Calendar;

import javax.net.ssl.KeyManager;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import javax.net.ssl.X509ExtendedKeyManager;
import javax.security.auth.x500.X500Principal;

/**
 * TLS identity for {@link LanShareServer} — a per-install, self-signed EC
 * P-256 certificate generated by AndroidKeyStore (which mints the
 * self-signed X.509 alongside the keypair, so no BouncyCastle, no hand-
 * rolled DER, and the private key never leaves the keystore).
 *
 * <p><b>Threat model this buys:</b> the receiver's browser can't verify a
 * self-signed cert (one "connection not private" interstitial, expected and
 * explained on the sender sheet), but the handshake still negotiates
 * ephemeral-key cipher suites (ECDHE) — so a PASSIVE sniffer on hostile
 * Wi-Fi gets ciphertext it can never decrypt, even if it records everything:
 * the file bytes, the PIN in the QR URL, and the session cookie all stop
 * being readable off the air. What it deliberately does NOT defeat is an
 * ACTIVE man-in-the-middle presenting its own self-signed cert — the
 * receiver has no way to tell the two apart; pinned-cert verification needs
 * a native client on both ends (the LocalSend-protocol upgrade path).
 *
 * <p>Per-install (not per-session) on purpose: the fingerprint stays stable
 * across shares, so a browser's stored "proceed" exception keeps working.
 *
 * <p>The key managers are built EXPLICITLY (a fixed single-alias
 * {@link X509ExtendedKeyManager}) rather than through
 * {@code KeyManagerFactory.init(keyStore, null)} — the default PKIX factory
 * is unreliable at selecting AndroidKeyStore entries (it can silently
 * choose no alias, leaving the server certless; every cipher suite then
 * fails and the client sees the connection closed with no response —
 * observed as ERR_CONNECTION_CLOSED in Brave). Handing conscrypt the
 * private key + chain directly removes the selection step entirely.
 *
 * <p>Failure here is non-fatal by design — {@link #getServerContext()}
 * returns null and the server falls back to plain HTTP (the pre-TLS
 * behavior) rather than breaking sharing on exotic keystore implementations.
 */
public final class LanShareTls {

    private static final String TAG = LanShareTls.class.getSimpleName();
    private static final String KEY_ALIAS = "lanshare-tls";
    private static final String ANDROID_KEY_STORE = "AndroidKeyStore";
    private static final int CERT_VALIDITY_YEARS = 20;

    private static SSLContext sCachedContext;

    private LanShareTls() {
    }

    /**
     * The server-side SSLContext backed by the keystore identity, or null
     * when TLS can't be set up (caller falls back to plain HTTP).
     */
    @Nullable
    public static synchronized SSLContext getServerContext() {
        if (sCachedContext != null) {
            return sCachedContext;
        }
        try {
            KeyStore keyStore = KeyStore.getInstance(ANDROID_KEY_STORE);
            keyStore.load(null);
            if (!keyStore.containsAlias(KEY_ALIAS)) {
                generateIdentity();
            }
            PrivateKey privateKey = (PrivateKey) keyStore.getKey(KEY_ALIAS, null);
            Certificate[] storedChain = keyStore.getCertificateChain(KEY_ALIAS);
            if (privateKey == null || storedChain == null || storedChain.length == 0) {
                Log.e(TAG, "keystore returned no usable identity");
                return null;
            }
            X509Certificate[] chain = new X509Certificate[storedChain.length];
            for (int i = 0; i < storedChain.length; i++) {
                chain[i] = (X509Certificate) storedChain[i];
            }
            SSLContext context = SSLContext.getInstance("TLS");
            context.init(new KeyManager[]{new FixedKeyManager(privateKey, chain)}, null, null);
            sCachedContext = context;
        } catch (Exception e) {
            Log.e(TAG, "TLS identity unavailable — LAN share falls back to plain HTTP", e);
        }
        return sCachedContext;
    }

    private static void generateIdentity() throws Exception {
        Calendar notBefore = Calendar.getInstance();
        notBefore.add(Calendar.DAY_OF_YEAR, -1);
        Calendar notAfter = Calendar.getInstance();
        notAfter.add(Calendar.YEAR, CERT_VALIDITY_YEARS);

        KeyPairGenerator generator = KeyPairGenerator.getInstance(
                KeyProperties.KEY_ALGORITHM_EC, ANDROID_KEY_STORE);
        KeyGenParameterSpec spec = new KeyGenParameterSpec.Builder(
                KEY_ALIAS, KeyProperties.PURPOSE_SIGN)
                .setDigests(KeyProperties.DIGEST_SHA256, KeyProperties.DIGEST_SHA384,
                        KeyProperties.DIGEST_SHA512)
                .setCertificateSubject(new X500Principal("CN=Firedown LAN share"))
                .setCertificateSerialNumber(BigInteger.valueOf(System.currentTimeMillis()))
                .setCertificateNotBefore(notBefore.getTime())
                .setCertificateNotAfter(notAfter.getTime())
                .build();
        generator.initialize(spec);
        generator.generateKeyPair();
    }

    /**
     * One key, one cert, no selection logic: every server-alias query
     * answers with the keystore identity. Client-side queries return null
     * (this context never authenticates as a client).
     */
    private static final class FixedKeyManager extends X509ExtendedKeyManager {

        private final PrivateKey mPrivateKey;
        private final X509Certificate[] mChain;

        FixedKeyManager(PrivateKey privateKey, X509Certificate[] chain) {
            this.mPrivateKey = privateKey;
            this.mChain = chain;
        }

        @Override
        public String chooseServerAlias(String keyType, Principal[] issuers, Socket socket) {
            return isCompatible(keyType) ? KEY_ALIAS : null;
        }

        @Override
        public String chooseEngineServerAlias(String keyType, Principal[] issuers,
                                              SSLEngine engine) {
            return isCompatible(keyType) ? KEY_ALIAS : null;
        }

        @Override
        public String[] getServerAliases(String keyType, Principal[] issuers) {
            return isCompatible(keyType) ? new String[]{KEY_ALIAS} : null;
        }

        @Override
        public PrivateKey getPrivateKey(String alias) {
            return KEY_ALIAS.equals(alias) ? mPrivateKey : null;
        }

        @Override
        public X509Certificate[] getCertificateChain(String alias) {
            return KEY_ALIAS.equals(alias) ? mChain.clone() : null;
        }

        @Override
        public String chooseClientAlias(String[] keyTypes, Principal[] issuers, Socket socket) {
            return null;
        }

        @Override
        public String chooseEngineClientAlias(String[] keyTypes, Principal[] issuers,
                                              SSLEngine engine) {
            return null;
        }

        @Override
        public String[] getClientAliases(String keyType, Principal[] issuers) {
            return null;
        }

        private boolean isCompatible(@Nullable String keyType) {
            if (keyType == null) {
                return false;
            }
            // Conscrypt asks for "EC" for ECDSA-authenticated suites; accept
            // the historical "ECDSA"/"EC_EC" spellings defensively.
            return keyType.equals(mPrivateKey.getAlgorithm())
                    || keyType.startsWith("EC");
        }
    }
}
