package com.solarized.firedown.sync.crypto;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.bouncycastle.crypto.ec.CustomNamedCurves;
import org.bouncycastle.crypto.params.ECDomainParameters;
import org.bouncycastle.math.ec.ECPoint;
import org.junit.Test;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.KeyFactory;
import java.security.interfaces.ECPrivateKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Arrays;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;

/**
 * Pins {@link PairSeal} to the SHARED pairing vector — the same bytes the web
 * client's own test reads.
 *
 * <p>The fixture below is copied verbatim from
 * {@code firedown-website/tools/pair-seal.json}, generated by
 * {@code fd-pair-test.mjs} (which seals with node/OpenSSL, an implementation
 * sharing no code with either client). Copied rather than loaded because that
 * is how every other shared vector in this package is carried
 * ({@link CryptoTest}, {@code BlindSignatureTest}) — the two repos cannot see
 * each other's files.
 *
 * <p>Why this test earns its place: a pairing failure is SILENT on every layer.
 * A wrong HKDF info string, a field in the wrong order, a coordinate padded
 * differently — each produces a well-formed blob the browser simply cannot
 * open, and the user sees "the pairing data could not be opened" with nothing
 * naming the side that is wrong. Asserting against bytes produced elsewhere is
 * what makes that fail here instead.
 *
 * <p>Deliberately Android-free (a plain JVM unit test), which is why
 * {@link PairSeal} uses {@code java.util.Base64}: with
 * {@code unitTests.returnDefaultValues} the Android one would silently return
 * null rather than fail.
 */
public class PairSealTest {

    private static final String PAIR_ID = "FIXTURE_PAIR_ID_0001";

    private static final String BROWSER_PUB_HEX =
            "04b53ba26e83a85f6f7604369f9c93da1fa071e61b0e431040872f35a3d2fb3938"
                    + "e92bc1254c0bc2fd2bd70670ae27c9524fa902b0500f301035819133ab50c009";

    private static final String BROWSER_PRIV_PKCS8_HEX =
            "308187020100301306072a8648ce3d020106082a8648ce3d030107046d306b0201"
                    + "010420687920e7807612e3e3be881b8a9424dbee096c0dde15b703200bef3ee6"
                    + "d8de2ea14403420004b53ba26e83a85f6f7604369f9c93da1fa071e61b0e4310"
                    + "40872f35a3d2fb3938e92bc1254c0bc2fd2bd70670ae27c9524fa902b0500f30"
                    + "1035819133ab50c009";

    /** Sealed by node/OpenSSL for the key pair above — must open here. */
    private static final String SEALED_HEX =
            "46445052310104158f59bcfb893296428617b483585c6f1112e163a371a01f83d6"
                    + "b244e1ea6a0dfd69249561b32de1097e8a6ece5afabebc7576571774374d1d43"
                    + "2eac7897aaed28f863a54b8c2d5eba64f6bdf3d92a3fa1bb5ee8da44c5ba4fa6"
                    + "8854a0b53318766dd14d6286a02dd816cfbb09a227cca9a2fc22746ec9abfb8c"
                    + "a2fa7c793e0aa07fd59e373381290525d229eb90be9d3adf63a10145c25ad205"
                    + "34fa07eb81db1da38897f0d4b9e708e2f012";

    private static final String ACCOUNT_ID_HEX = "0102030405060708090a0b0c0d0e0f10";
    private static final String AUTH_SEED_HEX =
            "404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f";
    private static final String STORAGE_KEY_HEX =
            "808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f";

    private static final String VERIFICATION_CODE = "103966";

    private static final ECDomainParameters CURVE;

    static {
        var params = CustomNamedCurves.getByName("secp256r1");
        CURVE = new ECDomainParameters(params.getCurve(), params.getG(), params.getN(), params.getH());
    }

    /* ───────────────────────── the shared vector ───────────────────────── */

    /**
     * THE cross-implementation assertion: a blob sealed by the web test's
     * OpenSSL "phone" opens here to the exact expected keys. If this fails, the
     * two clients have diverged on the wire format and pairing is broken in
     * BOTH directions, however well each side's own round-trip passes.
     */
    @Test
    public void opensTheSharedFixture() throws Exception {
        byte[] sealed = hex(SEALED_HEX);
        byte[][] out = open(sealed, hex(BROWSER_PRIV_PKCS8_HEX), hex(BROWSER_PUB_HEX), PAIR_ID);

        assertArrayEquals("account id", hex(ACCOUNT_ID_HEX), out[0]);
        assertArrayEquals("auth seed", hex(AUTH_SEED_HEX), out[1]);
        assertArrayEquals("storage key", hex(STORAGE_KEY_HEX), out[2]);
    }

    /**
     * The verification code is the anti-phishing check the USER performs, so
     * the two screens must compute the same six digits from the same inputs —
     * a mismatch would make every legitimate pairing look like an attack.
     */
    @Test
    public void verificationCodeMatchesTheWebClient() {
        assertEquals(VERIFICATION_CODE, PairSeal.verificationCode(PAIR_ID, hex(BROWSER_PUB_HEX)));
    }

    /* ──────────────────────────── our own seal ─────────────────────────── */

    @Test
    public void sealRoundTripsThroughAnIndependentOpener() throws Exception {
        byte[] accountId = hex(ACCOUNT_ID_HEX);
        byte[] authSeed = hex(AUTH_SEED_HEX);
        byte[] storageKey = hex(STORAGE_KEY_HEX);

        byte[] sealed = PairSeal.seal(PAIR_ID, hex(BROWSER_PUB_HEX), accountId, authSeed, storageKey);

        assertEquals("FDPR1", new String(Arrays.copyOf(sealed, 5), StandardCharsets.US_ASCII));
        assertEquals("version", 1, sealed[5]);
        assertEquals("uncompressed ephemeral point", 0x04, sealed[6] & 0xff);

        byte[][] out = open(sealed, hex(BROWSER_PRIV_PKCS8_HEX), hex(BROWSER_PUB_HEX), PAIR_ID);
        assertArrayEquals(accountId, out[0]);
        assertArrayEquals(authSeed, out[1]);
        assertArrayEquals(storageKey, out[2]);
    }

    /**
     * The blob is bound to the pairing id, so one captured from a real pairing
     * cannot be replayed into a session an attacker started.
     */
    @Test
    public void sealIsBoundToThePairingId() throws Exception {
        byte[] sealed = PairSeal.seal(PAIR_ID, hex(BROWSER_PUB_HEX),
                hex(ACCOUNT_ID_HEX), hex(AUTH_SEED_HEX), hex(STORAGE_KEY_HEX));
        try {
            open(sealed, hex(BROWSER_PRIV_PKCS8_HEX), hex(BROWSER_PUB_HEX), "A_DIFFERENT_PAIR_ID");
            org.junit.Assert.fail("a blob opened under the wrong pairing id");
        } catch (Exception expected) {
            // GCM authentication failure — exactly what should happen.
        }
    }

    /* ────────────────────────────── parsing ────────────────────────────── */

    @Test
    public void parsesTheDeepLinkAndTheBareCode() {
        String payload = "FDP1." + PAIR_ID + "." + b64url(hex(BROWSER_PUB_HEX));

        PairSeal.Ref viaLink = PairSeal.parse("firedown://pair/" + payload);
        assertNotNull(viaLink);
        assertEquals(PAIR_ID, viaLink.pairId);
        assertArrayEquals(hex(BROWSER_PUB_HEX), viaLink.pubkey);

        PairSeal.Ref bare = PairSeal.parse(payload);
        assertNotNull(bare);
        assertEquals(viaLink.pubkeyB64, bare.pubkeyB64);
    }

    @Test
    public void rejectsMalformedPayloads() {
        assertNull(PairSeal.parse(null));
        assertNull(PairSeal.parse(""));
        assertNull("wrong prefix", PairSeal.parse("FDS1.abc.def"));
        assertNull("no separator", PairSeal.parse("FDP1." + PAIR_ID));
        assertNull("empty key", PairSeal.parse("FDP1." + PAIR_ID + "."));
        assertNull("short id", PairSeal.parse("FDP1.x." + b64url(hex(BROWSER_PUB_HEX))));
        // A truncated key: right alphabet, wrong length.
        assertNull(PairSeal.parse("FDP1." + PAIR_ID + "." + b64url(new byte[32])));
    }

    /**
     * An INVALID-CURVE point is the classic way to attack ECDH — feed a point
     * on a weak curve and read the private scalar out of the shared secret. It
     * must be refused at parse, before any multiplication happens.
     */
    @Test
    public void rejectsAPointNotOnTheCurve() {
        byte[] bogus = hex(BROWSER_PUB_HEX);
        bogus[40] ^= 0x01; // perturb Y — no longer satisfies the curve equation
        assertNull(PairSeal.parse("FDP1." + PAIR_ID + "." + b64url(bogus)));

        byte[] wrongPrefix = hex(BROWSER_PUB_HEX);
        wrongPrefix[0] = 0x02; // compressed marker on a 65-byte body
        assertNull(PairSeal.parse("FDP1." + PAIR_ID + "." + b64url(wrongPrefix)));
    }

    @Test
    public void verificationCodeIsSixDigitsAndSessionBound() {
        String a = PairSeal.verificationCode(PAIR_ID, hex(BROWSER_PUB_HEX));
        assertTrue("six digits: " + a, a.matches("\\d{6}"));
        assertEquals("deterministic", a, PairSeal.verificationCode(PAIR_ID, hex(BROWSER_PUB_HEX)));

        String otherId = PairSeal.verificationCode("OTHER_PAIR_ID_00001", hex(BROWSER_PUB_HEX));
        org.junit.Assert.assertNotEquals("changes with the pairing id", a, otherId);

        byte[] otherKey = hex(BROWSER_PUB_HEX);
        otherKey[64] ^= 0x01;
        org.junit.Assert.assertNotEquals("changes with the key", a,
                PairSeal.verificationCode(PAIR_ID, otherKey));
    }

    /* ───────────────────────────── the opener ──────────────────────────── */

    /**
     * The BROWSER's side, rebuilt from the format spec alone — deliberately not
     * calling into PairSeal, so a mistake shared with the sealer cannot cancel
     * itself out and pass.
     */
    private static byte[][] open(byte[] sealed, byte[] pkcs8, byte[] browserPub, String pairId)
            throws Exception {
        byte[] phonePub = Arrays.copyOfRange(sealed, 6, 6 + 65);
        byte[] iv = Arrays.copyOfRange(sealed, 71, 83);
        byte[] body = Arrays.copyOfRange(sealed, 83, sealed.length);

        ECPrivateKey priv = (ECPrivateKey) KeyFactory.getInstance("EC")
                .generatePrivate(new PKCS8EncodedKeySpec(pkcs8));
        BigInteger d = priv.getS();
        ECPoint shared = CURVE.getCurve().decodePoint(phonePub).multiply(d).normalize();
        byte[] z = be32(shared.getAffineXCoord().toBigInteger());

        byte[] info = concat("firedown/pair/v1".getBytes(StandardCharsets.US_ASCII),
                pairId.getBytes(StandardCharsets.UTF_8), browserPub, phonePub);
        byte[] key = Hkdf.expand(Hkdf.extract(new byte[0], z), info, 32);

        Cipher c = Cipher.getInstance("AES/GCM/NoPadding");
        c.init(Cipher.DECRYPT_MODE, new SecretKeySpec(key, "AES"), new GCMParameterSpec(128, iv));
        byte[] plain = c.doFinal(body);
        assertEquals("plaintext length", 80, plain.length);

        return new byte[][]{
                Arrays.copyOfRange(plain, 0, 16),
                Arrays.copyOfRange(plain, 16, 48),
                Arrays.copyOfRange(plain, 48, 80),
        };
    }

    private static byte[] be32(BigInteger v) {
        byte[] raw = v.toByteArray();
        byte[] out = new byte[32];
        if (raw.length > 32) {
            System.arraycopy(raw, raw.length - 32, out, 0, 32);
        } else {
            System.arraycopy(raw, 0, out, 32 - raw.length, raw.length);
        }
        return out;
    }

    private static byte[] concat(byte[]... parts) {
        int len = 0;
        for (byte[] p : parts) {
            len += p.length;
        }
        byte[] out = new byte[len];
        int off = 0;
        for (byte[] p : parts) {
            System.arraycopy(p, 0, out, off, p.length);
            off += p.length;
        }
        return out;
    }

    private static String b64url(byte[] b) {
        return java.util.Base64.getUrlEncoder().withoutPadding().encodeToString(b);
    }

    private static byte[] hex(String s) {
        byte[] out = new byte[s.length() / 2];
        for (int i = 0; i < out.length; i++) {
            out[i] = (byte) Integer.parseInt(s.substring(i * 2, i * 2 + 2), 16);
        }
        return out;
    }
}
