#!/usr/bin/env python3
"""Splices the REAL sessions-file reader and writer out of app/src into one
harness class, so the checks run the shipped code and not a copy of it.

Lifted verbatim (modulo `private` -> package-private on the signature line, so
the harness can call them, and an optional mutation for teeth-checking):
  GeckoStateDataRepository: the version/key constants, sanitizeInlineField,
    readDocumentStrict, readEntityStrict, readEntity, next{String,Long,Int,
    Boolean}Safe
  GeckoStateObserver: writeEntity, orEmpty
  GeckoStateEntity: the KEYS class (the real key strings)
android.util.JsonReader/JsonToken/JsonWriter are swapped for Gson's, which the
Android classes were derived from (same API, same semantics for everything the
readers use — nextInt/nextLong accept NUMBER and STRING, throw without
consuming on a bad parse, skipValue is type-agnostic).

usage: splice.py <repo-root> <out-dir> [--mutate=nogate|noskip]
"""
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
out = Path(sys.argv[2])
mutate = next((a.split('=', 1)[1] for a in sys.argv[3:] if a.startswith('--mutate=')), None)

REPO = root / 'app/src/main/java/com/solarized/firedown/data/repository/GeckoStateDataRepository.java'
OBS = root / 'app/src/main/java/com/solarized/firedown/data/observer/GeckoStateObserver.java'
ENT = root / 'app/src/main/java/com/solarized/firedown/data/entity/GeckoStateEntity.java'


def lines_of(path):
    return path.read_text(encoding='utf-8').split('\n')


def extract_method(lines, signature_re):
    """A method at 4-space indent: from its signature line (plus the javadoc
    directly above, for context) to the first line that is exactly '    }'."""
    idx = [n for n, l in enumerate(lines) if re.match(signature_re, l)]
    if len(idx) != 1:
        raise SystemExit(f'expected one match for {signature_re!r}, got {len(idx)}')
    i = idx[0]
    j = i
    while lines[j] != '    }':
        j += 1
    body = lines[i:j + 1]
    body[0] = re.sub(r'^(\s+)private ', r'\1', body[0])
    return '\n'.join(body)


def extract_constant(lines, name):
    idx = [n for n, l in enumerate(lines) if re.match(rf'\s+(public |private )?static final \w+ {name} = ', l)]
    if len(idx) != 1:
        raise SystemExit(f'expected one constant {name}, got {len(idx)}')
    return re.sub(r'^(\s+)private ', r'\1', lines[idx[0]])


repo = lines_of(REPO)
obs = lines_of(OBS)
ent = lines_of(ENT)

constants = '\n'.join(extract_constant(repo, c) for c in [
    'SESSION_FILE_VERSION', 'MIN_SUPPORTED_SESSION_FILE_VERSION',
    'LEGACY_KEYS_BELOW_VERSION', 'KEY_VERSION', 'KEY_TABS',
    'MAX_INLINE_FIELD_CHARS', 'MAX_INLINE_DATA_URI_CHARS'])

methods = [
    extract_method(repo, r'\s+public static String sanitizeInlineField\(String'),
    extract_method(repo, r'\s+private List<GeckoStateEntity> readDocumentStrict\(JsonReader'),
    extract_method(repo, r'\s+private GeckoStateEntity readEntityStrict\(JsonReader'),
    extract_method(repo, r'\s+private GeckoStateEntity readEntity\(JsonReader'),
    extract_method(repo, r'\s+private static String nextStringSafe\('),
    extract_method(repo, r'\s+private static long nextLongSafe\('),
    extract_method(repo, r'\s+private static int nextIntSafe\('),
    extract_method(repo, r'\s+private static boolean nextBooleanSafe\('),
    extract_method(obs, r'\s+private void writeEntity\(JsonWriter'),
    extract_method(obs, r'\s+private static String orEmpty\('),
]
real = '\n\n'.join(methods)

if mutate == 'nogate':
    # The version gate never fires: a retired key is skipped in EVERY version.
    real2 = real.replace('if (version >= LEGACY_KEYS_BELOW_VERSION) {', 'if (false) {')
elif mutate == 'noskip':
    # The skip is gone: a retired key throws in EVERY version.
    real2 = real.replace('if (version >= LEGACY_KEYS_BELOW_VERSION) {', 'if (true) {')
elif mutate is None:
    real2 = real
else:
    raise SystemExit(f'unknown mutation {mutate}')
if mutate and real2 == real:
    raise SystemExit(f'mutation {mutate} did not apply — the gate moved?')
real = real2

keys_start = [n for n, l in enumerate(ent) if l == '    public static final class KEYS {']
if len(keys_start) != 1:
    raise SystemExit('KEYS class not found')
k = keys_start[0]
j = k
while ent[j] != '    }':
    j += 1
keys = '\n'.join(ent[k:j + 1])

pkg = out / 'com/solarized/firedown/harness'
pkg.mkdir(parents=True, exist_ok=True)

(pkg / 'SessionsReal.java').write_text(f'''package com.solarized.firedown.harness;

// GENERATED by splice.py from app/src — do not edit. Mutation: {mutate}

import android.content.Context;

import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@SuppressWarnings("all")
final class SessionsReal {{

    final Context mContext = null;

{constants}

{real}
}}
''', encoding='utf-8')

(pkg / 'GeckoStateEntity.java').write_text(f'''package com.solarized.firedown.harness;

// GENERATED by splice.py — a plain holder with the setters/getters the real
// reader and writer call, plus the REAL KEYS class lifted from app/src.

@SuppressWarnings("all")
final class GeckoStateEntity {{
    long creationDate;
    long lastAccess;
    String icon = "";
    String thumb = "";
    String title = "";
    int id;
    String sessionState = "";
    String sessionStateRef = "";
    int parentId;
    String uri = "";
    boolean backward, forward, desktop, fullScreen, home, active;

    GeckoStateEntity(boolean home) {{ this.home = home; }}

    void setCreationDate(long v) {{ creationDate = v; }}
    void setLastAccess(long v) {{ lastAccess = v; }}
    void setIcon(String v) {{ icon = v; }}
    void setThumb(String v) {{ thumb = v; }}
    void setTitle(String v) {{ title = v; }}
    void setId(int v) {{ id = v; }}
    void setSessionState(String v) {{ sessionState = v; }}
    void setSessionStateRef(String v) {{ sessionStateRef = v; }}
    void setParentId(int v) {{ parentId = v; }}
    void setUri(String v) {{ uri = v; }}
    void setCanGoBackward(boolean v) {{ backward = v; }}
    void setCanGoForward(boolean v) {{ forward = v; }}
    void setDesktop(boolean v) {{ desktop = v; }}
    void setFullScreen(boolean v) {{ fullScreen = v; }}
    void setHome(boolean v) {{ home = v; }}
    void setActive(boolean v) {{ active = v; }}

    long getCreationDate() {{ return creationDate; }}
    long getLastAccess() {{ return lastAccess; }}
    String getIcon() {{ return icon; }}
    String getThumb() {{ return thumb; }}
    String getTitle() {{ return title; }}
    int getId() {{ return id; }}
    String getSessionState() {{ return sessionState; }}
    String getSessionStateRef() {{ return sessionStateRef; }}
    int getParentId() {{ return parentId; }}
    String getUri() {{ return uri; }}
    boolean canGoBackward() {{ return backward; }}
    boolean canGoForward() {{ return forward; }}
    boolean isDesktop() {{ return desktop; }}
    boolean isFullScreen() {{ return fullScreen; }}
    boolean isHome() {{ return home; }}
    boolean isActive() {{ return active; }}

{keys}
}}
''', encoding='utf-8')
print(f'spliced {len(methods)} methods + KEYS (mutation: {mutate})')
